version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is is db folder
  db:
    image: mysql:8.0.32
    platform: 'linux/x86_64'
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
